### ISSUE TITLE
Vytvořit / najít společnou tabulkovou komponentu pro admin sekci

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#108]
@jhavelik : kdybys o něčem věděl, nebo někde něco našel, tak řekni

**Comment by jhavelik** [comment]
@SmallhillCZ už jsem nad tím přemýšlel, ono to asi moc vyřešit nejde.

Možnost je udělat prostě responzivní tabulku: https://getbootstrap.com/docs/4.0/content/tables/ a pak nějak zkusit pro menší zařízení vynechat nějaký sloupce. To je to co dělají s různými dashboardy jinde, např: https://colorlib.com/polygon/srtdash/index.html

**Comment by SmallhillCZ** [comment]
Asi bude stačit direktiva co přidá nějaké funkcionality (řazení, výběr řádků) a nějaké třídy (bootstrap responsivní tabulka)

**Comment by SmallhillCZ** [comment]
No společná už je, je to komponenta `<admin-table>` zbytek asi řešit nebudeme.
