### ISSUE TITLE
export dat do google kalendáře

### ISSUE THREAD

**Issue by TomasNeumann** [bosancz/bosan.cz#124]
Všechny vícedenní akce jsou o poslední den kratší, než je jejich oficiální konec na našich stránkách

**Comment by SmallhillCZ** [comment]
Hele když kouknu do toho exportu kalendáře, je to v pořádku. Máš k tomu nějaký další info? Nemáš třeba blbě nastavenou časovou zónu?

**Comment by SmallhillCZ** [comment]
Tak koukám, ale že mi to v Google Calendar dělá taky. Po pročtení x fór na internetu jsem prostě přidal den ke konci.

**Comment by TomasNeumann** [comment]
Taky řešení, působí to jako podivný problém ...

čt 13. 12. 2018 21:46 odesílatel Martin Kopeček <notifications@github.com>
napsal:

**Comment by SmallhillCZ** [comment]
On iCal je vůbec podivný formát ;)
