### ISSUE TITLE
Postavit fotky za autentifikaci

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#137]
Zatím jsou veřejné (a to i ty, co jsou draft), při stahování se úplně obchází server, jsou přímo nabízeny nginx ze složky fotek, stačí znát ObjectId alba a ObjectId fotky.

Otázka jestli výše zmíněné ObjectId nejsou dostatečným zabezpečením, jedná se o 2*24 víceméně náhodných znaků.

**Comment by elenfant** [comment]
Myslím, že prozatím to určitě stačí.

**Comment by SmallhillCZ** [comment]
OK
