### ISSUE TITLE
Číslo účtu

### ISSUE THREAD

**Issue by piskot1111** [bosancz/bosan.cz#144]
Ahoj, možná jsem to jen nenašel, ale na stránkách chybí číslo účtu. Spusta rodičů mi pak píše a já jim ho musím posílat.

Dík 
Piškot

**Comment by elenfant** [comment]
Určitě bych tam hodil všechno to, co Kopec citoval.
Nejlepší mi přijde dát to do patičky: vyhodit ty tři "sub-linky" KONTAKTY (co jsou jen kotvy) a místo nich hodit ten odstavec. A text KONTAKTY udělat jako link (trapně stejně jako v menu)...
"Praha 4, 147 00" může být na jednom řádku, čímž se dostáváme na celkem 6 řádků a to by nemuselo vypadat blbě.

Taky by to chtělo mít někde link na KONDOR určitě... To jsem si vůbec nevšiml, že nemáme.
Něco ve stylu: Jsme členy: KONDOR, ČRDM, ČSK (až budeme :)), což by mohl být čtvrtý sloupec patičky.

**Comment by DavidTvrdy** [comment]
Dneska jsem dostal od začátku roku zhruba čtrnáctý a patnáctý mail o tom, jaké že je naše číslo účtu.
Poslat jim číslo účtu mi sice trvá tak 15 vteřin, ale většina rodičů si dobře pamatuje, že to šlo vždycky na stránkách najít, a tak nejsou zrovna spokojený s tím, že to tam teď hledají marně, na což se odpovídá poměrně blbě.

**Comment by jhavelik** [comment]
Jo sorry pripravil jsem to temer na bedrichove, jen jsem se nedostal k tomu to dotahnout. Navrhy v priloze
![desktop](https://user-images.githubusercontent.com/5928448/55025678-b6963f00-5001-11e9-87c3-984ee42e8e59.PNG)
![mobile](https://user-images.githubusercontent.com/5928448/55025679-b72ed580-5001-11e9-9bb5-337a7b41f2cf.PNG)

Ještě tam teda nejsou ty věci o kondoru, ale to asi neni takova priorita.

@SmallhillCZ pokud vam to prijde OK staci mergnout: https://github.com/bosancz/bosan.cz/pull/179

**Comment by jhavelik** [comment]
BTW me by zajimalo co to je za usecase ze nekdo hleda cislo uctu? Plati prispevky, tabor? Predpokladam ze prispevky posilaji oddilaci nejakym mailem kde je VS a cislo uctu, tabor opet potrebuji VS ktery je na prihlasce (zaroven je tam asi i cislo uctu).

**Comment by DavidTvrdy** [comment]
Super, díky!
Platí příspěvky, tábor.. Na příspěvky posílám č. účtu s VS rovnou, to je většinou v pohodě. 
Ale hodně rodičů se zeptá (aspoň u nás) mailem na účet kvůli táboru. Účet i VS jsou na přihlášce, ale tu už většinou mezitím odevzdají vyplněnou, a číslo účtu si nepřepíšou. Myslím, že jsou prostě zvyklí, že se to někde na stránkách dá najít, když to zrovna potřebujou, nebo si toho ani na přihlášce nevšimnou.

**Comment by SmallhillCZ** [comment]
Je to tam, akorát to nikdo nezavřel.
