### ISSUE TITLE
Vyhledávání v databázi při přidávání členů na akci

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#146]
Řazení podle abecedy je poměrně nepraktický, vzhledem k tomu, kolik je tam lidí. Hledání podle jména je fajn, ale při hledání 30 lidí je to podobně náročný jako projíždět celou databázi.
Přidal bych možnost filtrovat podle oddílu a tam bych řadil lidi podle věku/funkce.

**Comment by SmallhillCZ** [comment]
Mně přišlo, že když zadáš první tři písmenka přezdívky, tak už máš člověka a je to hned, ale zkusim tam nějak zakomponovat aspoň oddíly.

**Comment by DavidTvrdy** [comment]
No, když vyplňuju účastníky, tak si jich pár zapamatuju a pak pořád dokola píšu tři písmenka, kliknu, přepíšu tři písmenka atd. Zatímco s možností filtrovat podle oddílů by mi stačilo zapamatovat si lidi z oddílu, kliknout na filtr, naklikat lidi atd.. To mi přijde výrazně rychlejší.
