### ISSUE TITLE
Kompatibilita staré a nové správy akcí

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#148]
Ve staré a nové interní sekci jdou u akce upravovat vždy jiné věci.
Konkrétně: 

V nové sekci nemůžu udělat vůbec nic se stavem svojí akce (teda tlačítka smazat a zrušit tam jsou, tak někdo asi může), ve staré trochu (přepínat mezi v přípravě a publikováno).

Ve staré sekci nejde nic dělat s ohláškou a účtováním.

Ve straré sekci nefungují účastníci, zobrazují se podivně a nejde je přidávat.

**Comment by SmallhillCZ** [comment]
Stará sekce bude postupně upozaděná a skončí jen jako tabulka, kterou pak logocky nebudou moct otevřít všichni (pak by si taky mohli treba schvalovat akce, že ;) ). Každopádně jí teď ne udu aktualizovat, pokud daná věc bude fungovat v nové.

**Comment by SmallhillCZ** [comment]
Ohledně chybějících stavů ve staré, to je v řešení.

**Comment by SmallhillCZ** [comment]
Stavy vyřešeny
