### ISSUE TITLE
Popisky alb se na mobilu nezobrazují celé

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#152]
Reported by Sirka:
![image](https://user-images.githubusercontent.com/1273865/51912853-8a7d8980-23d5-11e9-9e5c-7e79c6af94ae.png)

**Comment by jhavelik** [comment]
Hm... to bude oříšek, jde o to že album má pevnou výšku (kvůli scrolování v galerii), takže nevím jestli s tím něco uděláme. Nastavil jsem tam tusim ellipsize aby to udelalo alespon 3 tecky ale nejak to ocividne nefunguje... @SmallhillCZ pevne vysky se asi nezbavime co?

**Comment by SmallhillCZ** [comment]
Nj, to mi nedošlo :( Tady v o nás ta pevná výška potřeba není. Ale ve fotogalerii to asi problém bude.
