### ISSUE TITLE
Galerie - Zamezit nechtěnému zrušení uploadu

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#153]
Sirka [10:35 PM]
Čau, nevím jestli se to už řešilo, ale při nahrávání fotek do galerie musím zůstat na té "záložce" náhrát fotky a když ní vyjdu tak se všechny nahraný i nenahraný fotky smažou... Stejně tak u informací i po uložení... Jo a při nahrávání se fotky přehází že návaznost na ně je ta tam...

**Comment by DavidTvrdy** [comment]
Taky mám problém s řazením fotek, když jich zkusím do fronty na nahrání natáhnout víc najednou, tak se tam seřadí jinak než podle jména souboru. Tudíž je tam musím natahávat po jedné, jestli si je teda nechci nechat rozházet.

**Comment by SmallhillCZ** [comment]
@DavidTvrdy: řazení ve frontě by mělo být jedno, protože řazení pro zobrazení má jiná pravidla než kdy se fotka nahrála.
