### ISSUE TITLE
Upravit info o albu v galerii - řadit našeptávání akcí dle termínu

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#157]
Chci udělat album k táboru ... ukazuje mi deset akcí z minulého tisíciletí :), pokud si nepamatuju přesný název akce (a staré programy stále nemáme), tak nemám šanci tábor najít.

Líbí se mi, že se mi zobrazuje termín akce, což pomůže při shodném názvu, to je super.

**Comment by SmallhillCZ** [comment]
Hotovo.
