### ISSUE TITLE
Mobilní zobrazení se snaží vnutit zástupce interní sekce na domovskou obrazovku moc často

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#162]
Na mobilu mi teď pořád vyskakuje možnost 'přidat zástupce na domovsou obrazovku' bosan.cz/interni, a to klidně několikrát po sobě, a to i když zrovna nejsem v interní. Je to dost otravný, sice je tam možnost 'Dnes již nezobrazovat', ale to předpokládám budu muset označovat každý den znovu.
Tuším, že to nebude prohlížečem, doteď ani jinde se to nedělo/neděje.

**Comment by DavidTvrdy** [comment]
Aha, tlačítko 'Dnes již nezobrazovat' ani nic nedělá.

**Comment by DavidTvrdy** [comment]
Tak mi nefunguje ani tlačítko OK, zástupce nikde nevidím.
Jestli je to tím, že můj prohlížeč nemá práva přidávat zástupce na domovskou obrazovku, tak mi to ale nijak nenaznačuje.

**Comment by SmallhillCZ** [comment]
Tak si to dej na domovskou stránku :-D

Tohle je bohužel v roli prohlížeče. My jen dáme najevo, že tu funkcionalitu
podoprujeme, ale to okénko v moci nemáme.

Pokud jsi na Androidu v Chromu, tak to není jen o odkazu na domovskou
obrazovku, ale o tom, že se ti web nainstaluje jako regulérní aplikace,
bude v seznamu aplikací a tak.

**Comment by SmallhillCZ** [comment]
Hm... tak to nevim. Koukneme se na to příští víkend, ok?

**Comment by DavidTvrdy** [comment]
Jasně, budu si s tím ještě chvíli hrát a uvidím..

**Comment by SmallhillCZ** [comment]
je vtipný, že většinou se řeší opačný problém, tj. jak přimět prohlížeč, aby to okénko vůbec zobrazil, protože ani to nejde ovládat. Prohlížeč si sám nějak vyhodnotí, zda je to vhodné a zda bys mohl mít zájem.

**Comment by DavidTvrdy** [comment]
Aha, tak v Chromu na Androidu se to chová normálně bez problému. Tak mám dementní prohlížeč..

**Comment by DavidTvrdy** [comment]
Akorát bych čekal, že by se to mělo zobrazovat, když budu v interní v nastavení účtu->aplikace, a ne jinde..

**Comment by SmallhillCZ** [comment]
A co máš za prohlížeč?

**Comment by DavidTvrdy** [comment]
Používám to co jsem měl předinstalovaný.. Jmenuje se Prohlížeč

**Comment by SmallhillCZ** [comment]
Tohle je asi spíš problém prohlížeče. Nevim, jak bych to ovlivnil. Tak uzavírám.
