### ISSUE TITLE
Řazení záznamů v členské databázi

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#164]
1) Záznamy v databázi se teď řadí podle data/času poslední úpravy + podle aktivní/neaktivní. Lepší řazení mi přijde podle funkce/role + podle aktivní/neaktivní.

2) Hezky je to seřazené v okně při přidávání účastníků akce, tam se ale zase naopak pletou i lidi označení jako neaktivní, hodil bych je tam taky na konec.

**Comment by DavidTvrdy** [comment]
Add2) K tomu mě ještě napadlo, že by se při výběru vedoucích akce mohly zobrazovat jen seznamy vedoucích a instruktorů místo celé databáze.

**Comment by DavidTvrdy** [comment]
@SmallhillCZ  Ještě pořád se to podle mě chová divně..

Zdá se mi, že se to teď řadí podle:
1) aktivní - neaktivní
2) nespecifikované členství - člen i nečlen
3) oddíl
4) funkce
5) přezdívka
Což způsobuje rozházení různých lidí stejného oddílu pryč od sebe.

Přišlo by mi lepší:
1) aktivní - neaktivní
2) oddíl
3) člen - nečlen a nespecifikované členství
4) funkce
5) přezdívka (nebo datum narození)

K tomu členství - přestavoval bych si to tak, že ty, kdo chodí na schůzky a mají zaplacené příspěvky, označím jako členy a ostatní, tj. děti na akce a tábor, označím jako nečleny. Potom při prohlížení oddílové databáze uvidím nejdřív všechny členy (protože mě zajímají spíš) a potom až všechny nečleny(=děti jen na tábor), protože ty pravděpodobně zrovna nehledám.

Navíc, při přidávání účastníka akce se databáze řadí ještě jinak:
1) oddíl
2) funkce
3) přezdívka

Udělal bych to tam úplně stejně:
1) aktivita
2) oddíl
3) členství
4) funkce
5) přezdívka nebo datum narození

**Comment by SmallhillCZ** [comment]
Řadí se to aspoň podle 356643cbfbf2cc2b94cc0ce1617fcbaadfe8e97d "inactive group -role nickname", tj.
1. aktivní/neaktivní
2. oddíl
3. funkce
4. přezdívka

**Comment by DavidTvrdy** [comment]
Aha, ale takhle se mi to nezobrazuje, ještě tam musí nějakou roli hrát to členství..

**Comment by DavidTvrdy** [comment]
A když z databáze přidávám člena k akci, tak se mi to taky zobrazuje úplně jinak..

**Comment by SmallhillCZ** [comment]
vyřešeno
