### ISSUE TITLE
Nelze se přihlásit 

### ISSUE THREAD

**Issue by Zralocek1** [bosancz/bosan.cz#167]
Web mě nenechá přihlásit žádným volitelný způsobem do interní sekce. U možnosti přihlásit se pomocí GMail mě to překlikne na na mail zralok@bosan.cz a nepřihlásí a v snaze poslat odkaz na přihlášení mi to napsalo, že žádný mail (rejzek.kubik@seznam.cz a zralok@bosan.cz) a uživatelský jméno (Žralok, Zralok, zralok, žralok) není validním na odeslání přihlašovacího odkazu.

**Comment by SmallhillCZ** [comment]
Zkusil jsem teď poslat odkaz na zralok@bosan.cz a fungovalo to (aspoň to napsalo, že OK). Co ti to hlásí,, popř. co používáš za prohížeč?
