### ISSUE TITLE
Vyhledávání ve fotogalerii dle názvu/akce

### ISSUE THREAD

**Issue by Goliash2** [bosancz/bosan.cz#171]
Přidat vyhledávácí pole - třeba chci fotky z konkrétní akce a nevím, kdy přesně byla...

**Comment by SmallhillCZ** [comment]
CTRL+F?

**Comment by DavidTvrdy** [comment]
Ctrl+F to zvládá.. Jedině kdybych chtěl hledat v galerii na mobilu, tak tam asi podobný triky neznám.

**Comment by SmallhillCZ** [comment]
na mobilu to taky jde, ale je fakt že asi i bude hodně lidí, co na to nepřijdou. já mám vlastně hlavní problém v tom, že nevím, kam bych takové tlačítko dal

**Comment by DavidTvrdy** [comment]
No, zatím jsem na to přišel jenom v prohlížeči, v aplikaci ne..

**Comment by jhavelik** [comment]
Já ani tak nevidím problém v tom kam umístit nějaký vyhledávající pole, ať je to button nebo cokoliv, otázka je spíš jak budeme zobrazovat výsledek toho hledání? Co si představujete? Nějaký dropdown který zobrazí všechny alba co jsme podle vstupu vyfiltrovali? Na proklik pak do detail alba?

**Comment by DavidTvrdy** [comment]
Mě přijde praktický přesně to, co dělá Ctrl+F.. Ale pokud jde udělat tenhle trik všude (tj. i v aplikaci na mobilu), pak by takový vyhledávání bylo zbytečný.

Ten dropdown má možná tu vadu, že u akcí se stejným/podobným jménem by člověk nemusel na prvních pár pokusů trefit přesně to album, které měl na mysli. Zase na druhou stranu pořád by to asi bylo rychlejší než projíždět postupně celou fotogalerii.

Nejideálnější, co mě teď napadlo, by bylo filtrovat podle vstupu celou tu galerii, že by postupně neodpovídající alba mizely a že by se zároveň i upravoval ten ukazatel roků vpravo:) Ale chápu že to asi jen tak lehko nepůjde..
