### ISSUE TITLE
Účetnictví - chytřejší přidávání výdajů

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#178]
Po přidání nového výdaje do účetnictví akce by se mohlo automaticky vyplnit políčko 'Číslo' na "V#", kde za # by se samo doplnilo další číslo. Teďka je potřeba všechno vypisovat ručně.

Stejně tak by se mohl částečně vyplňovat sám 'Typ výdaje' podle nějakých klíčových slov v 'Popisu', třeba když je popis jídlo, Tesco, Billa atp., tak by se tam přednastavil typ Potraviny.

**Comment by SmallhillCZ** [comment]
Nice :) Jak bude čas, udělám to.

**Comment by DavidTvrdy** [comment]
Tohle už je asi vyřešený přidáváním výdajů podle typu výdaje.
