### ISSUE TITLE
Menu lišta odskakuje od horního okraje

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#184]
![Screenshot_2019-04-04-11-24-47-917_com android chrome](https://user-images.githubusercontent.com/47000101/55547644-05af3480-56d2-11e9-8f80-71af21fdc55d.png)

Občas se mi stane, že ten blok s menu apod. odskočí od horního okraje obrazovky. 
Myslím, že je to když otevřu stránku, sjedu kus dolů, pak se zjistí, že je k dispozici nová verze stránek. (Což normálně oznamuje ta žlutá věc, která ale asi zůstává nahoře místo aby jela dolů se mnou.)

**Comment by SmallhillCZ** [comment]
Jo, to bude přesně tím. Asi stačí přidělat position:fixed.
