### ISSUE TITLE
Výška alba v timeline view

### ISSUE THREAD

**Issue by Goliash2** [bosancz/bosan.cz#186]
Původně byla výška alba fixnutá na 300px, ale to pak schovávalo popis alba a odkaz "Otevřít album" v mobilním zobrazení u alb s dlouhým názvem na víc řádků. S těmi 300px ale nějak počítá scroller vpravo. Zamyslet se, jestli takto nechat s tím, že je to i tak plus mínus ok nebo vymyslet jinak.

**Comment by SmallhillCZ** [comment]
Tak po bližším prozkoumání se 300px na album nikde jinde nepoužívám, pouze umístění labelů se řeší poměrově (tj. pokud je album v půlce podle čísel, dá se to do půlky). To, čím, se to bude lišit od reality je asi dost málo na to to řešit. Zavírám tedy i issue.

**Comment by SmallhillCZ** [comment]
aha, tak to nebude tak jednoduché... způsobuje to chyby při načítání alb:
![image](https://user-images.githubusercontent.com/1273865/55720890-32c95300-5a02-11e9-98b6-2e3629ae2758.png)

**Comment by SmallhillCZ** [comment]
Totiž tím, že jsou načtená alba delší, než dummy alba (ty mají 300 px), tak se to celé prodlouží.

**Comment by SmallhillCZ** [comment]
@Goliash2: nemůže být třeba na mobilu menší font, aby se to tam vešlo?

**Comment by SmallhillCZ** [comment]
Asi to nějak funguje.
