### ISSUE TITLE
Účastníky akce může zobrazit jen vedoucí dané akce

### ISSUE THREAD

**Issue by Goliash2** [bosancz/bosan.cz#191]
Účastníci akcí jsou zobrazováni jen po rozkliknutí akce v sekci Moje akce, takže si je nikdo, kromě vedoucího dané akce nemůže zobrazit. Což je trošku škoda - třeba při vytváření popisků do galerie (pokud je vytváří někdo, kdo není vedený přímo jako vedoucí akce) nebo když se chce vedoucí oddílu podívat, které děti mu jezdí na akce. Asi by se dal seznam účastníků zobrazovat v přehledu akcí ve správě obsahu.

**Comment by SmallhillCZ** [comment]
Jo, tam bych se rád nějak zamyslel nad zobrazení a editací akcí. Zatím moc nemám jasný koncept a nechce se mi programovat polotovar. To zobrazení účastníků by ale šlo.
