### ISSUE TITLE
Na stránce k táboru mi chybí nějaká fotka v košilích (aby to vypadalo, že to má taky trochu řád)

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#193]

**Comment by SmallhillCZ** [comment]
@elenfant nechceš ktomu něoc vybrat? nebo to mám zavřít?

**Comment by Grejdy** [comment]
Už mám pro tento účel jednu fotku vybranou. Snad se v blízké době dostanu k implementaci (a vyřešení těch dalších asi tří issue, co mám aktuálně v plánu). Ale Fotky z tábora už mám hotový, takže už to snad bude brzo:-)
![original](https://github.com/bosancz/bosan.cz/assets/82664677/8b3771a7-9647-4312-af9c-80daa88cd0f4)
