### ISSUE TITLE
Mobilní - Interní -> Moje akce -> Úprava akce : Přihláška se nezobrazuje

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#195]
Nahraná přihláška se na mobilu nezobrazí jako na počítači, místo ní je tam jenom další tlačítko navíc:

![Screenshot_2019-04-18-09-12-10-534_com android chrome](https://user-images.githubusercontent.com/47000101/56349769-8a697a80-61c9-11e9-933f-3aa101263508.png)
---
![obrazek](https://user-images.githubusercontent.com/47000101/56349788-981f0000-61c9-11e9-8eef-980090b84a43.png)

**Comment by SmallhillCZ** [comment]
Jojo, vim o tom :-D Dneska to spravim (dám pryč to tlačítko navíc).

Ale i tak dík za issue, kdybych si toho náhodou nevšiml, tak by se to bez
ní neopravilo.
