### ISSUE TITLE
Mobilní - Interní -> Moje akce -> Úprava akce : Přidávání výdajů namá tlačítko 'zrušit'

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#196]
Na mobilu se při přidávání nového výdaje do účetnictví nezobrazí tlačítko 'Zrušit úpravu'.

![Screenshot_2019-04-18-10-59-36-803_com android chrome](https://user-images.githubusercontent.com/47000101/56349976-05cb2c00-61ca-11e9-9509-5a8e06690879.png)
---
![obrazek](https://user-images.githubusercontent.com/47000101/56350003-111e5780-61ca-11e9-81eb-d179642430d7.png)

**Comment by SmallhillCZ** [comment]
Je to záměr - nevejde se tam. Resp. pak by se tam nevešly ty formuláře.

To je takový problém, co už jsem přešil předtím. Ještě se nad tím zamyslím, jestli tu editaci neudělám dvouřádkovou třeba.

**Comment by DavidTvrdy** [comment]
No jo, toho jsem si nevšiml..

**Comment by SmallhillCZ** [comment]
Vyřeším v Issue #216

**Comment by SmallhillCZ** [comment]
Bude celé nové účtování
