### ISSUE TITLE
Mobilní - Interní -> Moje akce -> Úprava akce : Obdélníčky reprezentující účastníky jsou moc velké

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#197]
Na mobilu zabírá každý účastník hodně místa, zmenšil bych trochu ty obdélníčky.
Na mobilu se obdélníčky dotýkají s těmi nad/pod, na počítači mají mezi sebou mezery, což je přehlednější.

![Screenshot_2019-04-18-09-12-25-923_com android chrome](https://user-images.githubusercontent.com/47000101/56350209-8be77280-61ca-11e9-9f4a-c0691901673d.png)
---
![obrazek](https://user-images.githubusercontent.com/47000101/56350228-9570da80-61ca-11e9-9923-c41e90073afe.png)

**Comment by SmallhillCZ** [comment]
Hm... jsem si moc neověřil, jak to bude vypadat O:-)

Trochu je zmenším, ale bojoval jsem tam s tím, že na malé zas nejde komfortně kliknout.

**Comment by DavidTvrdy** [comment]
To je pravda, zase ale když budou o něco menší + trošku od sebe odsazené, tak by člověk klikat vedle moc nemusel..

**Comment by SmallhillCZ** [comment]
Jojo, zkusim to nějak odladit. Navíc ty máš oproti mě nějaký malý telefon, mně se jich tam vejde víc.

**Comment by SmallhillCZ** [comment]
Asi mě to donutí nějak sjednotit ty akce, abych si mohl zobrazit nějaké tvoje ;)

**Comment by SmallhillCZ** [comment]
@DavidTvrdy: co máš za mobil?

**Comment by DavidTvrdy** [comment]
https://xiaomistore.cz/obchod/mobilni-telefon-xiaomi-redmi-4x-global/

**Comment by SmallhillCZ** [comment]
@DavidTvrdy: Mělo by být vyřešeno posledním updatem, prosím o potvrzení a případné uzavření.
