### ISSUE TITLE
Fotogalrie : Velikost poslední fotky na mobilu/ Velikosti a odsazení fotek na počítači

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#198]
1) Na mobilu se poslední fotka každého alba zobrazuje jinak velká (menší) než všechny ostatní.

![Screenshot_2019-04-18-09-11-27-612_com android chrome](https://user-images.githubusercontent.com/47000101/56350493-2fd11e00-61cb-11e9-966a-9e7138286757.png)
---
2) Na počítači jsou fotky zobrazené různě velké a s různým odsazením, což někdy vypadá docela nepřirozeně:)

![obrazek](https://user-images.githubusercontent.com/47000101/56350595-7292f600-61cb-11e9-9652-d6d62cc62ec6.png)

**Comment by SmallhillCZ** [comment]
1) To je dané tím systémem vykreslování. Zamyslím se, jestli nemá smysl ho pro mobil nějak obejít.
2) Eh to je něco hodně špatně...

**Comment by SmallhillCZ** [comment]
... ale mám klasický debuggerský problém "mě to funguje". Co máš za prohlížeč a tak? Příp. nemůžeš s tím nějak zapokusovat kdy to nastává? Vypadá to, že se vždy poslední fotka z předchozího řádku nesprávmě zalomí na další.

![image](https://user-images.githubusercontent.com/1273865/56351177-ceaa4a00-61cc-11e9-8694-ec848b4280bd.png)

**Comment by DavidTvrdy** [comment]
Tak Chrome a Explorer v pohodě, Firefox má problém.
Myslím, že poslední fotka řádku skočí o jeden dolů. Což způsobí to, že je jinak velká (podle svého originálního řádku), a to, že ta další od ní není odsazená (protože si myslí, že je na začátku řádku, kde asi není odsazení).

**Comment by DavidTvrdy** [comment]
Neděje se to ale vždycky, jenom někdy.. Nevím kdy..

**Comment by SmallhillCZ** [comment]
Hm Firefox nějak divně zaokrouhluje. Zkusím takovou malou opravu a uvidíme

**Comment by SmallhillCZ** [comment]
Tak to vypadá, že to pomohlo. @DavidTvrdy, můžeš prosím potvrdit?

**Comment by DavidTvrdy** [comment]
Jojo, kouknu na to během odpoledne, až se zase dostanu k počítači..

**Comment by Goliash2** [comment]
Já to teď checknul a je to super. Měl jsem cachnutou starou verzi a ve firefoxu to fakt zobrazovalo předtím divně. Takže paráda, super práce :)

**Comment by SmallhillCZ** [comment]
No sem tam to furt o pixel uskakuje, asi by to chtělo nějaké lepší řešení. Ale vzhledem k tomu, že většina lidí podle mě jde rovnou na fotky a neotevírá album, tak je to asi jedno.

**Comment by DavidTvrdy** [comment]
Myslím, že je to takhle dost v pohodě..
