### ISSUE TITLE
Internet Explorer - Program : ikonky akcí

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#200]
Když jsem zkoušel, v jakých prohlížečích blbne ta fotogalerie, tak jsem náhodou narazil v Exploreru na takovýhle ikonky v programu akcí:

![obrazek](https://user-images.githubusercontent.com/47000101/56365377-04f9c080-61f1-11e9-9685-e5d2ba9e5cb4.png)

**Comment by SmallhillCZ** [comment]
Co je to za IE? Mě to v IE11 funguje.

**Comment by DavidTvrdy** [comment]
![obrazek](https://user-images.githubusercontent.com/47000101/56366558-b4d02d80-61f3-11e9-859c-e4ca6e75f8aa.png)

**Comment by SmallhillCZ** [comment]
Hele na to ladit jednotlivý verze IE asi fakt nemám :-D

![image](https://user-images.githubusercontent.com/1273865/56367381-6c197400-61f5-11e9-8770-302247f3b12d.png)

**Comment by DavidTvrdy** [comment]
:D
