### ISSUE TITLE
V programu nejde upravit akce

### ISSUE THREAD

**Issue by LeilaTolar** [bosancz/bosan.cz#201]
Nejde přidat vedoucí akce  - já jsem je přidala přes Správu obsahu, ale mělo by to jít i rovnou z Interní sekce, ne?

**Comment by elenfant** [comment]
Funguje v Přehledu (interni/moje/prehled) ale už ne při manuálním vyhledání sebe sama v sekci Akce (interni/obsah/akce) - testováno uživatelem test1.

**Comment by SmallhillCZ** [comment]
Tohle by mělo být vyřešeno posledním updatem, můžete někdo ověřit? @LeilaTolar , @elenfant , @DavidTvrdy ?

**Comment by LeilaTolar** [comment]
Pořad mi to nejde, resp. jde vybrat vedoucí, ale pak se tam nezobrazí a ani neuloží

**Comment by Goliash2** [comment]
Mobilní verze: Ve Správě obsahu v Akcích při výběru vedoucího nejde zavřít ten modal s výběrem vedoucích, ani tlačítko zpět nefunguje. Dal bych vedle tlačítka Vybrat ještě tlačítko zavřít nebo tak něco.. Zavřít to můžu jen refreshnutím stránky. Ale možná to je jen problém malého displaye, že nejde kouknout mimo ten modal.

**Comment by SmallhillCZ** [comment]
@LeilaTolar : počkala jsi na načtení nové verze? Tj. aktualizovat a počkat, než se zobrazí nahoře oranžový pruh a aktualizovat znovu? (chápu, je to debilní)

**Comment by LeilaTolar** [comment]
Nepočkala, funguje to 🙂

**Comment by SmallhillCZ** [comment]
@Goliash2 : Správa obsahu není vyvíjena, opravuji jen ty, co jsou pod loginem, byla by to duplicita práce. Časem se tam přesune vše. Akce se konkrétně vyřeší tím, že bude stejné editační okno, jako je to v Moje akce a tohle se smaže.
