### ISSUE TITLE
Firefox - program - přihláška k akci a její zobrazení

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#202]
Ve Firefoxu jsem si všiml, že přihláška na akci v programu se po kliknutí na odkaz začne stahovat, místo aby se zobrazila jako pdf v novém okně prohlížeče, jako to dělá třeba v IE a což předpokládám je správně.

Ne že by to bylo něco zásadního, ale narazil jsem na to..

**Comment by SmallhillCZ** [comment]
Stahování je nastavené schválně. Chrome totiž má problém přihlášku zobrazit, viz #138

**Comment by DavidTvrdy** [comment]
Aha, sorry, toho jsem si nevšiml..
