### ISSUE TITLE
Chybné formátování účetnictví - opravit v XLSX

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#203]
Teď jsem dělal účtování výjezdu a ta předvyplněná tabulka je dost super, je to asi tak dvacetkrát rychlejší než dřív!

Akorát to neumí u nečlenů napsat N, takže se to musí přepisovat ručně.
Taky jsem našel pár chyb ve formátu:

![obrazek](https://user-images.githubusercontent.com/47000101/57375711-68e32980-719e-11e9-954f-7b295845dec6.png)

**Comment by SmallhillCZ** [comment]
No to člen/nečlen je sice v databázi, ale nemá to žádnou vazbu na zaplacené příspěvky, takže je to dost random. V ideálním světě by se to samo vyplnilo podle zaplaceným příspěvků. V našem světě se zkusím dohodnout s Tyčkou, který jediný přesně ví, kdo má zaplaceno, že bych mu udělal nějaký jednoduchý interface na určování toho, kdo je a kdo není člen.

Dávám to do separátní Issue, v téhle budu řešit formátování
