### ISSUE TITLE
Chybné mazání položek v účtování

### ISSUE THREAD

**Issue by MichalSuhajek** [bosancz/bosan.cz#204]
Čau,

dělám účtování na webu. Když chceš nějakou položku smazat a klikneš na -, tak se umaže to pod ní a ne ta, kterou jsi chtěl umazat.

Šuhaj

**Comment by SmallhillCZ** [comment]
Jo hele já to celé předělám trochu v duchu těch účastníků a v rámci toho spravím

**Comment by SmallhillCZ** [comment]
Účtování bude teď celé nové
