### ISSUE TITLE
Vytváření programu

### ISSUE THREAD

**Issue by LeilaTolar** [bosancz/bosan.cz#205]
Jde jen o nápad, ale nebylo by možné mít z akcí přidaných na stránky předvyplněný formulář na vytvoření programu k tisku? Vlastně stejně jako to funguje s ohláškou a účtováním? Ušetřilo by to hromadu práce a času
Díky

**Comment by SmallhillCZ** [comment]
Jo to byl plán, ale někde to zapadlo.

**Comment by SmallhillCZ** [comment]
Tak zatim jsem udělal hezčí ten program pro rodiče

**Comment by SmallhillCZ** [comment]
@LeilaTolar : @krystofrezac ti tam udělal export do Wordu, co ty na to?

**Comment by LeilaTolar** [comment]
Ahoj, parada a díky :) Šlo by to ještě upravit tak, aby se exportovaly jen akce, které jsou v programu? Teď tam mám i všechny, které byly jen v přípravě @SmallhillCZ @krystofrezac

**Comment by SmallhillCZ** [comment]
opraveno :)
