### ISSUE TITLE
Přidat na stránku Kontakt hlavní vedoucí táborů

### ISSUE THREAD

**Issue by Goliash2** [bosancz/bosan.cz#219]
Máša říkala, že někteří rodiče nevěděli, kde na ni vzít telefon/mail. Nevím, kde hledali, ale je fakt, že bych taky čekal kontakt na stránce kontakt.

**Comment by Goliash2** [comment]
A je vtipné, že na stránce tábor je "Chceš vědět víc" button, který tě hodí na stránku kontaktů, kde ale kontakt na vedoucí táborů není :D

**Comment by SmallhillCZ** [comment]
Na zas tak skrytý to neno, je to na na https://bosan.cz/tabor...

**Comment by Goliash2** [comment]
Já vím, že to tam je

**Comment by Goliash2** [comment]
Je to jen komentář od Máši

**Comment by SmallhillCZ** [comment]
zahraný
