### ISSUE TITLE
Zarovnání stavu akce

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#220]
Předělat, nahradit třeba tečkou před názvem

![Screenshot_20190806-095504](https://user-images.githubusercontent.com/1273865/62521711-786f1e80-b830-11e9-96f0-e64e7eccaa0f.png)

**Comment by Goliash2** [comment]
Můžeme tam dát i tečku, ale nevím, jestli to bude všem jasné bez textu, zatím jsem jenom upravil zarovnání na mobilech a přemýšlím, že by se na mobilu možná dalo odřádkovat a v prvním řádku nechat jen název akce a v druhém třeba trochu menším fontem stav a datum

**Comment by Goliash2** [comment]
treba nejak takto 
![navrh](https://user-images.githubusercontent.com/38349508/62690587-3deeb880-b9cd-11e9-81f0-2711efa156bd.png)

**Comment by Goliash2** [comment]
Mozna by to bylo hezci i v desktop zobrazeni...
![test-b](https://user-images.githubusercontent.com/38349508/62691354-cc176e80-b9ce-11e9-88f5-45499a8fcb92.png)

**Comment by SmallhillCZ** [comment]
Zrušil bych nějak ten ```<sup></sup>```, je to ošklivý.

**Comment by elenfant** [comment]
> Zrušil bych nějak ten `<sup></sup>`, je to ošklivý.

Souhlas (použití `<sup>` mě trochu překvapuje). Na střed řádku by to vypadalo ideálně, ne?

**Comment by Goliash2** [comment]
Oki, smazal jsem <sup> a upravil řádkování podle toho mého návrhu - pushnul jsem to do produkce, tak se za chvilku můžete podívat a kdyžtak nikdo nebude nic mít, tak to zavřeme.
