### ISSUE TITLE
Posílání připravované akce ke schválení

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#221]
V sekci Moje akce nemůžu svojí připravovanou akci poslat ke schválení (nedostatečná oprávnění). Jde to udělat jenom přes Správu obsahu.

**Comment by Pat-sudo** [comment]
Áha, dík. Jdu sem napsat to samé, ale bez tebe bych nenašel možnost udělat to ve správě obsahu.

**Comment by SmallhillCZ** [comment]
Sry, no time :/ Ale kouknu na to co nejdříve

**Comment by SmallhillCZ** [comment]
sloučené sekce to vyřešily
