### ISSUE TITLE
Vodák roku

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#222]
U akcí chybí políčko pro zapsání ujetých kilometrů a vodák roku vůbec neumí rok 2019.

**Comment by SmallhillCZ** [comment]
Aha :-D Kouknu na to určitě.

**Comment by SmallhillCZ** [comment]
Je potřeba dodělat tlačítko pro spluté kilometry

**Comment by DavidTvrdy** [comment]
Tak po dalších debatách s oddíláky a ve výboru vzdělávání dětí pořád platí, že by se nám kolonka na ujeté kilometry hodila. Kdyby se v databázi navíc u každého člověka samo počítalo, kolik ujel kilometrů, bylo by to super.

**Comment by DavidTvrdy** [comment]
Řešení navrhnuté v #244 .
