### ISSUE TITLE
Zobrazení volných akcí na rozebrání

### ISSUE THREAD

**Issue by Pat-sudo** [bosancz/bosan.cz#224]
Leila má, a teď nevím jestli ve svém profilu, nebo ve správě obsahu ale to je celkem fuk), takový pěkný kalendář, kde vidí jaké akce se na jaký víkend plánují, co je již schválené, co se pouští za ČPV apod.  Nemohli bychom to vidět všichni namísto výpisů akcí pod sebou? Myslím, že by to každému pomohlo v plánování, neb by viděl co se kdy případně děje za ČPV a nemusel si to hledat vedle a také by viděl kde vycházejí nějaké volné víkendy a jak jsou akce rozložené a nemusel by si to dopočítávat a luštit z datumů.

**Comment by SmallhillCZ** [comment]
Jojo, mohli bychom nějakou variaci (bez tvorby akcí) dát na úvodní stránku

**Comment by SmallhillCZ** [comment]
Je tona úvodní stránce :) Ale řešíme, jak to z ní dát do vlastní a udělat to na úvodní hezčí
