### ISSUE TITLE
Formátování tlačítek tagů ve veřejné fotogalerii

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#225]
Pokud je u galerie spousta tagů a nevejdou se na jeden řádek (třeba ŠÁN 2019 I. turnus), nenaskládají se pod sebe moc hezky.

![image](https://user-images.githubusercontent.com/47000101/63594416-ae452e80-c5b6-11e9-8981-4ee303a09de4.png)

**Comment by Goliash2** [comment]
Jj, to jsem už taky zjistil. U sebe jsem testoval, že by bylo hezčí, kdyby byly ty tagy trošku menší... :)
![obrazek](https://user-images.githubusercontent.com/38349508/63594659-54913400-c5b7-11e9-9478-1b77ba65ff24.png)

**Comment by Goliash2** [comment]
Opravil jsem vysku radku tak, aby se tagy na vice radkach neprekryvaly. O velikosti se muzeme jeste pobavit. Minimalne na mobilu jsou fakt prilis velke a zabiraji velkou cast obrazovky.

**Comment by DavidTvrdy** [comment]
Výška řádku už je v poho.
Další problém je, jak se ty tlačítka na ty řádky vůbec skládají - nový řádek vznikne jedině tak, že je nějaký tag víceslovný, a to ještě tím způsobem, že ho to rozseká v půlce.

**Comment by DavidTvrdy** [comment]
Jinak na mobilu by klidně mohly být trošku menší, to je pravda.
Jinak na počítači mi to přijde velikost v pohodě.

**Comment by Goliash2** [comment]
Oki, tak ja je trosku zmensim jen pro mobil. To odradkovani je fakt zvlastni... na to taky kouknu.

**Comment by Goliash2** [comment]
Tak zalamovani vyreseno vlozenim fixni mezery mezi tagy a velikost pro mobilni zarizeni mirne zmensena

**Comment by DavidTvrdy** [comment]
Pořád se mi jeden tag klidně rozdělí na 2 řádky, když to uzná za vhodné.

Kromě toho, když na mobilu vyeru jeden tag a on se rozsvítí modře, tak přesahuje přes všechny okolní. Stejně tak bych ty první na řádku trochu odlepil od kraje, aspoň ať jsou celé vidět, když jsou vybrané.

**Comment by Goliash2** [comment]
Opraveno, pridan atribut nowrap pro tagy. Cely blok tagu jsem odsadil od kraju, takze tagy zacinaji a konci az dal od kraje a ne primo na kraji a jeste jsem trochu zvetsil velikost radku, aby se ani vybrane (modre zvyraznene) tagy neprekryvaly.
