### ISSUE TITLE
Fail při nahrávání fotek do galerie

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#228]
![obrazek](https://user-images.githubusercontent.com/47000101/66506483-b2c59800-eacd-11e9-8103-b84841786cbe.png)

**Comment by elenfant** [comment]
Dost možná bude souviset také s Pandičky chybou https://bosan.cz/interni/obsah/chyby/2048035985 (obecně uploud/store problém?).
Tuhle Mazákovu jsem v error logu teď na rychlo nenašel.

**Comment by SmallhillCZ** [comment]
Jo je to tak, už by to mělo být OK

**Comment by DavidTvrdy** [comment]
Tak už se mi zobrazuje stejná chyba zase..
