### ISSUE TITLE
Interní sekce / účtování akce / počet najetých km skupinovým vozem

### ISSUE THREAD

**Issue by jhavelik** [bosancz/bosan.cz#244]
**Popis problému**
Momentálně je pro hospodáře skupiny velmi problematické zjištění počtu najetých kilometrů skupinovým vozem. Položka ve výsledném excelu existuje, nicméně vedoucí akce na ní zapomínají a nevyplňují. Pak je nutné zpětné dohledávání najetých kilometrů proti knize jízd ve spolupráci se správcem vozu.

**Návrh řešení - hotfix**
Přidat do formuláře účtování akce položku "najeté km skupinovým vozem", aby jí vedoucí akce mohl explicitně vyplnit a vyplněné pole se promítlo do excelu.

**Návrh řešení - super improvement**
Zavést na webu sekci něco jako "Skupinový vůz", kde by se vedla zjednodušená kniha jízd s napojením na akce.

Představa:

- potřebuji na akci auto, napíšu správci auta, ten pokud ho vedoucímu půjčí označí akci jako že na ní auto je
- vedoucí akce před odesláním akce musí vyplnit nájezd kilometrů (začátek - konec), rozdíl se vyplní do účtování a následného exportu
- vše je pak k náhledu v interní sekci v kategorii auto, např. pokud je akce označená jako ta s autem a v dodaném účtování není vyplněno - nelze akci účtovat

**Comment by SmallhillCZ** [comment]
Jak rychle si představuješ ten 🔥HOT🔥 fix? :)

**Comment by jhavelik** [comment]
@SmallhillCZ představuji si tak měsíc až dva, ideálně do té doby než naplno vypukne vodácká sezóna a vůz bude více využívaný :)

**Comment by SmallhillCZ** [comment]
Okok, to snad zvládnem. Bohužel jsem poslední dobou dost vyblokovanej.

**Comment by SmallhillCZ** [comment]
No tak jsem to nezvládl :-D Ale už vim jak to udělat, bude to součást reportu, vyplní se tam jak proběhla akce, kolik km autem a kolik km na vodě.

**Comment by jhavelik** [comment]
@SmallhillCZ zavírám, jestli jsme to nepotřebovali do teď tak to nepotřebujeme :)
