### ISSUE TITLE
Ovládání kalendáře v přehledu

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#254]
(2) Nechceme přidat výběr měsíce a roku?

(3) Volné akce: Dal bych je rozhodně pod kalendář - bude to asi dost nekonečný seznam. Na PC mi vpravo od kalendáře vadí, nevidím ho celý a musím s ním posouvat.

**Comment by SmallhillCZ** [comment]
1 a 4 jsem dal jako #260 a #262

**Comment by SmallhillCZ** [comment]
2 a 3: ten kalendář tak debilně zabírá celou stránku. uavžuju že ho i s nějakým ovládáním dám jako zvlášť stránku a tady bude jen nějaký menší

**Comment by DavidTvrdy** [comment]
Zas je ten kalendář ale asi to, co tě pravděpodobně zajímá, když jdeš na kartu 'Přehled'.

Na mobilu mě pro něj žádný vylepšení nenapadlo, ale i tak tam je podle mě lepší než nic:)

**Comment by SmallhillCZ** [comment]
2) no mohl by být nějaký jednodušší, třeba jen na měsíc a když si chceš procházet jiné období než příští měsíc, tak si otevřeš stárnku a tam bude velký i s ovládáním?

3) tak se dá udělat aby se roloval v menším, aby nezabíral celou stránku když bude dlouhý

**Comment by DavidTvrdy** [comment]
To by obojí vyřešilo:)
