### ISSUE TITLE
Seznam a filtrování akcí

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#255]
(1) filtr: Na PC není.

(2) filtr: Když nemá co ukázat, tak ukáže výsledky minulého filtru místo ničeho.

(3) editace: Tlačítko 'Ke schválení' nezmění stav akce.

(4) seznam: Potřebuju tady vidět místo konání?

(5) seznam: Zmenšit rozestupy mezi akcemi, aby jich bylo vidět víc najednou.

**Comment by SmallhillCZ** [comment]
1) #263 

2) Můžeš rozvést?

3) #264

4) No asi nepotřebuješ. Můžu ho dát na konec aby na mobilu nepřekáže, nebo ho uplně odebrat.

5) Já to neumim udělat jinak na mobilu a na PC a na mobilu se pak blbě strefuje do jedný

**Comment by DavidTvrdy** [comment]
(2) Příklad: Dám si filtr na akce [rok 2020; stav Zrušená]. Ukážou se mi. Pak si změním filtr na [rok 2020; stav Vrácená k úpravám] - taková akce neexistuje - čekal bych, že nic neuvidím, ale zůstaly mi tam zobrazené výsledky předchozího filtrování.

**Comment by DavidTvrdy** [comment]
(5) Aha, ve stávající interní sekci je to o hodně jinak a nepřišlo mi to zas tak hrozný..

**Comment by SmallhillCZ** [comment]
nejdřív opravim to zobrazení filtru :-D pak se na to podívám

**Comment by DavidTvrdy** [comment]
(2) a (4) jsou pořád aktuální. Ale jsou to detaily..
