### ISSUE TITLE
TEST->Interní->Galerie

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#256]
- filtr: Když chci vidět jen zveřejněné galerie, ukáže mi to jen připravované.

- stránka alba: Tuhle stránku bych vyhodil a otevřel rovnou editaci.

- editace alba: Nejde spárovat s akcí, nejde změnit stav.

- editace alba: Po jakékoliv editaci potvrzené tlačítkem 'Uložit' změní stav na 'v přípravě', a navíc už mi nikdy příště neukazuje tlačítko 'otevřít na webu'.

- editace fotek: Nejde smazat fotka.

- editace fotky: Změna popisku se projeví po jeho úpravě v přehledu alba až po obnovení stránky. (PC)

- editace fotky: Odsadit pole pro úpravu popisku níž od fotky. (Mobilní)

**Comment by SmallhillCZ** [comment]
1) #265 

2) Jo to mě včera taky napadlo.

3) + 4) + 5) #267

4) Připravovanoou galerii si nemůžeš otevřít na webu, protože není veřejná.

5) #268

6) #269
