### ISSUE TITLE
Možnosti zobrazení sloupců v databázi

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#257]
(1) filtr: Na PC není.

(2) seznam: Posouvání seznamu doprava je na PC až úplně dole.

(3) seznam: Zmenšil bych rozestupy.

**Comment by SmallhillCZ** [comment]
1) #263 

2) To asi nejde jinak. Ale plánuju odebrat pár polí, aby se to tam vešlo. Pošleš mi screenshot jak to vypadá u tebe? Mělo by ho jít vložit sem CTRL+V

3) jak u akcí, na mobilu se na to pak blbě kliká.

**Comment by DavidTvrdy** [comment]
(2) Tak bych asi aspoň dal pryč Fukci a třeba Hodnost bych dal na konec..

![image](https://user-images.githubusercontent.com/47000101/78133486-ccadbb00-741e-11ea-9906-4c4274d55adc.png)

**Comment by SmallhillCZ** [comment]
Jako já jsem je hodně prohazoval ty sloupce a furt nevim který tam dát. Mám ty kategorie rozdělený takhle:

Role: dítě, instruktor, vedoucí - jde o pravomoce na webu ale i ve skupině, přístupy (má klíče atd)
Funkce: Pak některý veoducí jsou oddíláci, hospodář, revizor, hlavas, ale furt jsou i vedoucí, proto zvlášť kategorie
Hodnosti: To, co máš na košili.

Každý potřebuje něoc jinýho, tak nevim jestli tam neudělat třeba nějakou možnost zvolit si sloupce.

**Comment by DavidTvrdy** [comment]
Je pravda, že by se někomu mohl i sloupec Funkce hodit.
(Já jsem si představoval jenom tabulku svýho oddílu, kde se od sloupce Role v podstatě liší jen u mě a člunařů)

Ale možnost zvolit si sloupce by mohla být dobrá.

**Comment by SmallhillCZ** [comment]
Právě, ty jako oddílák máš uplně jiný přístup než třeba hospodář, který zas potřebuje filtrovat podle věku a města, nebo revizor, který chce zas vědět jak se třeba vzděláváme.

**Comment by DavidTvrdy** [comment]
Výběr sloupců je super!
