### ISSUE TITLE
TEST->Interní->Login

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#261]
- Třeba vteřinu nejdřív vidím 'Přehled', než mě to pošle na 'Login'.

**Comment by SmallhillCZ** [comment]
Jo, ale asi to není teď akutní. teoreticky se to i dá obejít aby tě to nenutilo přihlásit, ale ze serveru se ti nenačtou data, na která nemáš přístup a nebudeš moct měnit data, takže hrozba to neni.

Pro zatim uzavírám, někdy to třeba nějak vyřeším líp.
