### ISSUE TITLE
Nastylovat mapy

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#3]
Nebo třeba použít Mapy.cz

**Comment by Goliash2** [comment]
Jsem pro použít mapy.cz, příp. ještě lépe to udělat, jako na http://www.bosan.cz/new/kontakt.php kde tě to v mobilní verzi nechá vybrat :)

**Comment by SmallhillCZ** [comment]
A není lepší tu logiku toho, kterou appku vybereš nechat na mobilu? Android tě nechá vybrat, jestli to chceš otevřít v google mapách, nebo v Mapy.cz

**Comment by SmallhillCZ** [comment]
Je to moc práce a zanedbatelný přínos
