### ISSUE TITLE
Databáze ubytování

### ISSUE THREAD

**Issue by Pat-sudo** [bosancz/bosan.cz#320]
Bylo by možné přidat do interní sekce databázi ubytování, která byla na starých stránkách? Přišlo mi to celkem praktické.

**Comment by SmallhillCZ** [comment]
Já bych to možná vyřešil nějakým Google dokumentem spíš... nebo je tam nějaká konkrétní přidaná hodnota na webu?

**Comment by SmallhillCZ** [comment]
Vytvořil jsem google dokument zde: https://docs.google.com/spreadsheets/d/1U9uU7pCJICdhlp2vD9CNThmdfV5gHi9NiHkoDqLsOaw/edit#gid=942265602
