### ISSUE TITLE
Z galerie nejdou mazat fotky.

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#326]
Ikonka koše pod fotkou nefunguje. Když chci smazat fotku, musím smazat celé album a nahrát všechny ostatní fotky znovu.

**Comment by SmallhillCZ** [comment]
tak to už mi radši napiš a já ti jí nějak smažu kouzlem :)

jinak neboj, monituruju tu ty věci co tu píšete a sbírám síly an to se na to vrhnout a všechno to opravit...
