### ISSUE TITLE
Tábor - Stíny fotek, nejdou nějak nahezčit?

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#33]

**Comment by Goliash2** [comment]
No muzu je udelat min vyrazne a trochu vic rozmazat... treba takto: http://bosancz-ufon.smallhill.cz/tabor

**Comment by SmallhillCZ** [comment]
Co spíš něco, jako
```css
box-shadow: 0 0 10px rgba(0, 0, 0, 0.6);
```
?

**Comment by Goliash2** [comment]
Hotovo, vytvořena na to celá třída img-shadow, která je teď aplikovaná jak na fotky u stránky tábor, tak u částí schůzky, kanál a bazén
