### ISSUE TITLE
Stránka Aktuálně nezobrazuje poslední fotoalba

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#341]
Zběžnou kontrolou zvenčí mi přijde, že je problém někde v `Album.datePublished`, které je u všech posledních alb prázdné, přestože jsou alba zveřejněná.
https://bosan.cz/aktualne
(reported one behalf of Tyčka)

**Comment by DavidTvrdy** [comment]
#312

**Comment by SmallhillCZ** [comment]
ou jé.. je to tak. díky že mi to připomínáš

**Comment by elenfant** [comment]
GH neumí nějak linkovat tickety? Označovat jako duplikáty apod? Každopádně díky @DavidTvrdy za upozornění, přehlédl jsem.
