### ISSUE TITLE
Android - Interní: Při rozbalení Menu zůstává vidět tlačítko pro filtrování.

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#360]
Asi se to vyřeší v _nový mobile-first layout_, ale stejně:

Tlačítko pro více možností po otevření Menu zmizí, tlačítko pro filtrování zůstane vidět (a posune se víc doprava), asi by mělo taky zmizet.

**Comment by SmallhillCZ** [comment]
Jo, tohle bude uplně jinak
