### ISSUE TITLE
Upravit back button text

### ISSUE THREAD

**Issue by Goliash2** [bosancz/bosan.cz#376]
**Co se stalo?**
Na iOS je back button anglicky - stačí upravit
<ion-back-button
          [text]="zpět" _(nebo nechat prázdné)_
          >
</ion-back-button>

**Screenshoty**
![obrazek](https://user-images.githubusercontent.com/38349508/119462615-308cf480-bd41-11eb-9c86-8d61eba3197d.png)

**Zařízení:**
iOS

Až se dostanu k rozumnému compu můžu udělat pull request

**Comment by SmallhillCZ** [comment]
Nejde to nastavit nějak globálně? Nastavovat to u každého se mi moc nechce...

**Comment by SmallhillCZ** [comment]
Jde:

```ts
import { IonicModule } from '@ionic/angular';

@NgModule({
  ...
  imports: [
    BrowserModule,
    IonicModule.forRoot({
      backButtonText: 'Zpět'
    }),
    AppRoutingModule
  ],
  ...
})
```
