### ISSUE TITLE
Nejde načíst / uložit přihláška. 

### ISSUE THREAD

**Issue by JakubRejzek** [bosancz/bosan.cz#412]
**Co se stalo?**
Kroky k reprodukování chyby:
1. způsob: Pokus se uploadnout do tebou vedené akce přihlášku.
2. způsob: Pokus se stáhnout staré přihlášky
 
**Co jsem čekal/a**
1. způsob Úspěšné nahrání
2. způsob: Funkční PDF soubor

**Co jsem dostal**
2. Dostal jsem chybu při stahování a hlášku: "Chyba - Problém se serverem"
1. zp: Žádalo to po mě pdf soubor, ale byl nazván jako : "Adobe acrobat document" (žádá stále .pdf soubor, nebo libovolný soubor)
1. zp: Dostal jsem server error (500), a tento request result:
Request URL: https://interni.bosan.cz/api/events/6121e27f3979f2001ddf2b21/registration
Request Method: GET
Status Code: 500 
Remote Address: 185.8.165.228:443
Referrer Policy: strict-origin-when-cross-origin
content-length: 21
content-type: text/plain; charset=utf-8
date: Mon, 06 Sep 2021 09:13:42 GMT
etag: W/"15-/6VXivhc2MKdLfIkLcUE47K6aH0"
vary: Accept-Encoding
x-powered-by: Express
:authority: interni.bosan.cz
:method: GET
:path: /api/events/6121e27f3979f2001ddf2b21/registration
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: cs-CZ,cs;q=0.9
cookie: G_ENABLED_IDPS=google; _fbp=fb.1.1620238819933.318697687; G_ENABLED_IDPS=google; _gid=GA1.2.1661394856.1630917958; G_AUTHUSER_H=0; access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzgzZGUyNzBhYmUxODNiOWU1NjE0YzIiLCJyb2xlcyI6WyJjbGVuIiwidmVkb3VjaSIsInVzZXIiXSwibG9naW4iOiJ6cmFsb2siLCJtZW1iZXIiOiI1Yjc3NTZkYzJiMmFmMzZkN2Q5NDYwZGEiLCJncm91cCI6IjciLCJpYXQiOjE2MzA5MTc5NjYsImV4cCI6MTYzMTAwNDM2Nn0.oB_Vd1P5ED9luNLPvfZmRrNMoU8iWyKrqKqE-Vy0SAg; _ga=GA1.2.673525245.1620238819; _ga_CQNME2M1LP=GS1.1.1630917957.6.1.1630918907.59
sec-ch-ua: "Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: same-origin
sec-fetch-site: same-origin
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

**Screenshoty**
Pokud to jde, udělej screenshot (zmáčkni tlačítko PrtScr na klávesnici) a vlož ho sem pomocí CTRL+V

**Zařízení:**
- Zařízení: mobil / počítač
- Prohlížeč: Chrome / Safari / Seznam / Edge

**Comment by SmallhillCZ** [comment]
@JakubRejzek udělal jsem opravu (#414), poslal jsem ti invite, pak tě přidám abys zkontroloval a potvrdil
