### ISSUE TITLE
Aktualizovat text o bazénu ve veřejné sekci

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#432]
Obecný text k bazénům ve veřejné sekci v programu již neodpovídá skutečnosti a může být matoucí.
Konkrétně: bazény teď nejsou jednou měsíčně v neděli 16:30-19:30.

**Comment by Grejdy** [comment]
To myslím i zvládnu opravit (až se mi teda povede zprovoznit ten software k tomu:-)). Co všechno se tam má udělat? Změnit všechny časové údaje na neurčité (19:30 -> tři hodiny po srazu atp.), přepsat cenu (pro členy to teď má být myslím 100 kč, pro nečleny už si to nepamatuju), to je z bazénů asi vše?
A o kanálu a trénincích toho moc nevím, takže tam vůbe neodhadnu, co je tam špatně (krom toho, že by si trénink na káčku zasloužil taky nějakou fotku, což můžu jak nafotit, tak se pokusit implementovat, i když to už bude složitější, až zase nějaký bude).

**Comment by DavidTvrdy** [comment]
U tréninků v Troji bych změnil čas na "odpoledne".
U kajaků na Káčku má být v úterý (ne ve úterý), taky bych místo časů napsal odpoledne, protože časy se minulý rok každý týden měnily.

**Comment by elenfant** [comment]
> Ještě v úvodním textu bych nahradil "jednou měsíčně v neděli" za něco jiného, třeba "jednou měsíčně v sobotu nebo neděli"..

Dokonce dvakrát měsíčně. :)
