### ISSUE TITLE
Notifikace o změnách pro správce programu

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#495]
**Jaký problém tvůj nápad řeší?**
Vezmu si akci, dodám popisek a kliknu "KE SCHVÁLENÍ". Tímto okamžikem flow přechází na správce programu, který se o tom ale vůbec nijak nedozví. Takže já čekám čekám, až napíšu správcovi, který o tom nemá ani páru. Chápu, že správce nechodí na web každý den kontrolovat, jestli náhodou někdo nedal akci ke schválení...

**Popiš možnosti řešení**
Každá akce odeslaná ke schválení vygeneruje email pro správce programu, aby vše odsýpalo a akce zbytečně nečekaly ve vzduchoprázdnu.

**Comment by SmallhillCZ** [comment]
jo, no... https://github.com/bosancz/bosan.cz/issues/79

**Comment by SmallhillCZ** [comment]
duplikát
