### ISSUE TITLE
Nefunguje generování programu

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#499]
**Co se stalo?**
Tyčkovi to nefunguje prej vůbec a Járovi se to rozbilo

**Comment by elenfant** [comment]
Hele a mně to funguje. Na Win desktopu, +- latest Chrome, MS Word Version 2202 z Office 365 (Enterprise Channel).
Takže otázka: je rozdíl v
1. prohlížeči
2. wordu
3. mém admin přístupu do programu v interní sekci
4. něčem úplně jiném

**Comment by SmallhillCZ** [comment]
🤷‍♀️

To chce se ozvat Tyčkovi, jestli to je ještě problém a případně to s ním nějak zreprodukovat.
