### ISSUE TITLE
Vyměnit fotku Bošánu v /program za fotku Káčka.

### ISSUE THREAD

**Issue by MichaelMoncek** [bosancz/bosan.cz#503]
Na webu je v /program v sekci schůzky stará fotka Bošánu. Mohli bychom ji vyměnit za fotku Konstruktivy.

**Comment by Goliash2** [comment]
Jasný, určitě můžu. Takto na podzim by to mohlo být i pěkně barevné barevné :)

**Comment by jhavelik** [comment]
@Goliash2 Díky postni to sem nebo mě do mailu, pak to obratem vystavím na web.

**Comment by Goliash2** [comment]
@jhavelik Tak jsem se k tomu dostal až dneska. Zastavil jsem se u Káčka, ale bohužel jsem si nezkontroloval, zda mám nabitou baterku do drona, takže jsem vystartoval a za moment jsem měl low battery error. I tak jsem stihl udělat pár fotek a myslím, že by mohly stačit, jen teda jsou všechny z jednoho úhlu, takže není moc z čeho vybírat. Jsou na Google Drive v složce Propagace/Fotky.
