### ISSUE TITLE
Adresa loděnice není konzistentní s údaji v mapových aplikacích

### ISSUE THREAD

**Issue by DavidTvrdy** [bosancz/bosan.cz#505]
Má být V Náklích, ne V náklích.
![IMG_20221106_142758](https://user-images.githubusercontent.com/47000101/200174078-18f34faf-4a74-42e5-a29e-11cda3ff8df7.jpg)

**Comment by elenfant** [comment]
Proč si to myslíš? Jsem přesvědčený, že aktuální stav je to správně.

**Comment by Goliash2** [comment]
Jojo, to jsme řešili, před tiskem náborových letáků. Tak, jak to tam je teď uvedené to správně podle katastru, viz. https://nahlizenidokn.cuzk.cz/ZobrazObjekt.aspx?encrypted=NAHL~UyqvPADEwJuZ7RHNW_bI0y6OCyFRz0EAGfxLYC8-O9qgJ4lbW3VU9321__XGvSPu3CbMJXUsnUmHn_FWHeaxpeSmhopCMn-Z4VkAneJVJVSPoM1sVDEzHcwLOW2717BdMtS7QhiAKaUwPSo0LNVYkc_p-VGoQ48EO8BkR_syDvd8Emq2mWwXzn_1ReW_ZO7DRYFTCZ0DzAs4mZJIasWU_Q==

Ale souhlasím, že z pohledu češtiny by to mělo být jak píše Mazák. Třeba na Berounsku je ulice V Náklích s velkým N 😅

Jinak i podle katastru má ta ulice ke Káčku název Lodnická. Takže si myslím, že současný stav v katastru je značně  historický a ještě chybný a možná by stálo za to se ozvat a požádat o nápravu. Přeci jen loděnice v ulici Lodnická by byla víc sexy 😁

**Comment by DavidTvrdy** [comment]
Koukám, že jsem neudělal dostatečný průzkum:) Ale myšlenka byla, že máme v kontaktech ulici napsanou jinak, než jak ji vizualizují Mapy.cz nebo Google Maps, což může působit divně.
Je ale pravda, že i Mapy.cz mají název ulice všude vedený s malým písmenkem, ale vizualizují ho s velkým. Tady by možná šlo požádat o nápravu snadněji.
