### ISSUE TITLE
Prohodit ve veřejné sekci kontakty oddíláků s kontakty členů vedení

### ISSUE THREAD

**Issue by Grejdy** [bosancz/bosan.cz#555]
**Jaký problém tvůj nápad řeší?**
Zájemce o naší skupinu většinou zajímají víc oddíláci, než nějaký hospodář a revizor. Takhle se obávám, že budou všichni telefonovat členům vedení místo oddílákům, protože se k nim neproscrollujou (kór teď, když je vedoucích v sekci Vedení devět místo původních sedmi - předtím byl aspoň na počítači vidět nadpis pondělních oddíláků, teď potenciální zájemce vidí stránku devíti lidí a přemýšlí, jestli se má ptát, zda může přijít na schůzku, člena vedení, nebo mluvčího za Kondora)

**Popiš možnosti řešení**
Prostě dát členy vedení až pod oddíláky.

**Comment by Grejdy** [comment]
A s tím možná ještě souvisí: v zápatí jsou odkazy na kontakty, oddíláky pondělka a oddíláky středy a v praxi všechny akorát otevřou záložku kontakty - to by stálo za to buď zprovoznit (to je asi na samostatnou issue) nebo dva z těch odkazů smazat - tři identické odkazy pod sebou tam rozhodně být nemusí.

**Comment by DavidTvrdy** [comment]
> A s tím možná ještě souvisí: v zápatí jsou odkazy na kontakty, oddíláky pondělka a oddíláky středy a v praxi všechny akorát otevřou záložku kontakty - to by stálo za to buď zprovoznit (to je asi na samostatnou issue) nebo dva z těch odkazů smazat - tři identické odkazy pod sebou tam rozhodně být nemusí.

Ty odkazy jsou jiný, ale evidentně to nefunguje

**Comment by Grejdy** [comment]
> > A s tím možná ještě souvisí: v zápatí jsou odkazy na kontakty, oddíláky pondělka a oddíláky středy a v praxi všechny akorát otevřou záložku kontakty - to by stálo za to buď zprovoznit (to je asi na samostatnou issue) nebo dva z těch odkazů smazat - tři identické odkazy pod sebou tam rozhodně být nemusí.
> 
> Ty odkazy jsou jiný, ale evidentně to nefunguje

No samozřejmě, to mám na mysli.

**Comment by elenfant** [comment]
Já si vždycky myslel, že by tam bohatě stačil jen hlavní vedoucí a hospodář (a možná revizor). Nevím, proč by kdo chtěl kontaktovat někoho jiného z vedení. Nicméně když jsem se na to ptal lidí zvenčí, tak jsem občas slyšel, že víc lidí působí důvěryhodnějším dojmem - že jsme prostě velká organizace atd.
Ale osobně si pořád myslím, že mít tam kontakty na celé vedení nebo mluvčí KONDORa nedává moc smysl. :) Tenhle názor ale není nijak silný.

**Comment by Grejdy** [comment]
No, každopádně tihle nepodstatní lidi nemusí být nad oddílákama, kteří normálního rodiče asi zajímají spíš. (A já si teda taky myslím, že tam těch lidí máme zbytečně moc.)
