### ISSUE TITLE
Přidat nějaký obrázek ke kajakářským tréningům na káčku

### ISSUE THREAD

**Issue by Grejdy** [bosancz/bosan.cz#557]
Udělám, jen co se mi nějaký takový povede vytvořit. Jen ať to tu je, protože kajakářské tréningy ještě pár měsíců nebudou:-)

**Comment by jhavelik** [comment]
@Grejdy máme fotku?

**Comment by Grejdy** [comment]
Máme jednu. Snažil jsem se sehnat i druhou (něco na téma „dítě nastupující do kajaku“), ale ten jeden trénink, na který jsem mohl, jsem nakonec i vedl, takže jsem na focení neměl moc času a od té doby jsem se snažil poprosit o nějakou fotku ostatní, což neklaplo… takže buď tam můžu hodit zatím tu jednu, nebo můžem počkat na jaro, udělat další a dát je tam najednou.

**Comment by Grejdy** [comment]
Zatím nejlepší mám tuhle fotku. Možná by si zasloužila ještě trošku oříznout, ale jinak by tam mohla být dobrá. Ale za mě by si tam zasloužila ještě nějakou „kamarádku“ z takového toho pozadí (sedí se v tom takhle, pádlo se drží takhle, tady ho máš…)
![FOT00005](https://github.com/bosancz/bosan.cz/assets/82664677/a90df161-52b8-44c1-a9ba-a852260591c5)

**Comment by Grejdy** [comment]
Fotka výše nahrána na web jako „trening1.jpg“, ale zatím nezveřejněna - uveřejnit společně s druhou, až se jí povede vyfotit.
