### ISSUE TITLE
Odkaz na odebírání kalendáře akcí přes ical ve veřejné sekci, upravit metadata a zveřejnit

### ISSUE THREAD

**Issue by Grejdy** [bosancz/bosan.cz#558]
**Jaký problém tvůj nápad řeší?**
Člověk, kterého zajímá, jaké akce ho čekají, musí aktuálně pravidelně kontrolovat program na webu (nebo dávat pozor na nástupu:-)). Každopádně by mi přišlo hezké, kdyby si aktivní dítě/vedoucí/rodič mohl z webu zkopírovat do své kalendářové aplikace odkaz, přes který by se mu průběžně vypisovali akce do jeho kalendáře v telefonu/pc.

**Popiš možnosti řešení**
1) Zjistit, jestli náš kalendář v interní sekci (v budoucnu možná i ve veřejné?), tuhle funkci podporuje nativně (já jsem to z kódu nepoznal, ale nejsem v tomhle směru odborník)
2) Pokud je výsledek bodu 1 „ne“, tak to změnit (ideálně tak, aby byly rozdělené minimálně dětslé a vedoucovské akce, nejlépe aby pro každý oddíl/vedoucí/KP existoval jiný kalendář)
3) Dát odkaz(y) na web - třeba do zápatí jako rozbalovací nabídku

**Comment by SmallhillCZ** [comment]
Hehe ono to jde... https://bosan.cz/api/program/ical

nevim proč na to nemáme někde odkaz :-D

**Comment by Grejdy** [comment]
> Hehe ono to jde... https://bosan.cz/api/program/ical
> 
> nevim proč na to nemáme někde odkaz :-D

Supr. Myslíš, že by se dalo nějak zařídit, alby tam k vedoucímu akce místo info@bosan.cz dával jeho mail (co to je vůbec za mail to info?) a nějak se do něj promítalo, jestli je to dětská či vedoucovská akce? Protože jinak myslím, že opravdu stačí ten odkaz někam dát na stránky.

**Comment by SmallhillCZ** [comment]
Jo to by asi šlo. Zkusím to udělat ještě v té současné verzi.

**Comment by Grejdy** [comment]
Supr.
A mimochodem, co je ten info@bosan.cz zač. Když na to člověk pošle mail, komu přijde?

**Comment by SmallhillCZ** [comment]
vim já? asi @jhavelik teďka

**Comment by Grejdy** [comment]
Supr, teď už zbývá jenom hodit ten odkaz někam na web, což už zvládne i někdo z nás programátorů-nováčků. Díky

**Comment by Grejdy** [comment]
Je možný, že to přestalo fungovat?

**Comment by SmallhillCZ** [comment]
jo, odebral jsem jeden hack co jsme tam měli. s novou interní to bude ještě jinde, tak to pak nesmíme zapomenout změnit

https://interni.bosan.cz/api/program/ical

**Comment by Grejdy** [comment]
Takže bude lepší to přidat do veřejné až bude nová interní hotová.

**Comment by SmallhillCZ** [comment]
> Takže bude lepší to přidat do veřejné až bude nová interní hotová.

To bych zase zbytečně nečekal.

**Comment by Grejdy** [comment]
Teďka jsem koukal, že se tam zase u účastníků (resp. pořadatelů) píše mail info@bosan.cz (myslím, že dřív už tam byl správný mail) a že je tam jako účastník jeden člověk, i když to vedou dva.
Ale asi to teď tolik nehoří vzhledem k tomu, kolik jsem si v poslední době zvládl najít času na to pokusit se to dát do tý veřejný sekce.:-)

**Comment by Grejdy** [comment]
A oddíly, pro které je akce určená, tam koukám taky zase nejsou.

**Comment by SmallhillCZ** [comment]
ufff... protože jsem to nepřetáhl u té migrace, asi to ještě nebylo mergnutý a mergnul jsem to až potom.

**Comment by SmallhillCZ** [comment]
Píšu si to sem: https://github.com/bosancz/interni-sekce/issues/40

**Comment by Grejdy** [comment]
A napadlo mě, jestli by se to nedalo nastavit tak, aby se u celoskupinových akcí nevypisovaly do závorky všechny oddíly (že by se tam v takovém případě psalo „všichni“, nebo by tam nebylo napsáno nic a byly by takhle označený jen ty, co mají nějaké zvláštní složení (podzimky, tábory, akce pro vedoucí…)………jen takový částečně estetický detail:-).

**Comment by SmallhillCZ** [comment]
Jenom v icalu, nebo i na webu? Nám se to tehdá líbilo graficky, že je vidět kolik máme oddílů a že tam všichni můžou. V Tom icalu to být nemusí. Vtom icalu to ale možná vadí no.

**Comment by Grejdy** [comment]
Jenom v icalu. Na webu je to takhle dobrý, ale v tom kalendáři bude u spousty lidí ten název tak natěsnanej v nějakém okýnku, že tam stejně budou vidět bez rozkliknutí idálosti jenom třeba dva oddíly.
