### ISSUE TITLE
Nejde spustit vývoj!

### ISSUE THREAD

**Issue by Grejdy** [bosancz/bosan.cz#567]
Problém, na který jsme narazili na Bedřichově při pokusu rozběhnout u mě vývoj přes node. (Mám dojem, že jsme narazili na dvě věci, co je potřeba opravit, ale nepamatuju si tu druhou)

**Comment by Grejdy** [comment]
Mohu poprosit o nápravu @SmallhillCZ ?

**Comment by SmallhillCZ** [comment]
Jo, dneska se na to kouknu

**Comment by SmallhillCZ** [comment]
Máš k tomu nějaký ty konkrétní chyby, co jsme tam měli? Psal sis je někam do poznámkového bloku myslím

**Comment by SmallhillCZ** [comment]
Opravil jsem jen názvy konfigurací, možná že to bylo všechno?

https://github.com/bosancz/bosan.cz/tree/fix/development-environment

**Comment by SmallhillCZ** [comment]
Už jsem si vzpomněl, jde o to to aktualizovat tak, aby to běželo pod NodeJS 18 a nemusel jsi přepínat verze. Jdu na to...

**Comment by Grejdy** [comment]
> Opravil jsem jen názvy konfigurací ve veřejné, možná že to bylo všechno? Interní nám myslím nakonec fungovala, poté, co jsme odblokovali nějaké agresivní blokování cookies tvým prohlížečem.

Jo, byly to ty názvy konfigurací a byl to problém jenom u veřejné sekce. A tu aktualizaci bude taky záhodno udělat (a snad už to je vše, co tam nešlo)
