### ISSUE TITLE
Sdílení galerie na facebook

### ISSUE THREAD

**Issue by Kobtul** [bosancz/bosan.cz#69]
Aby se na facebooku natáhl náhled

**Comment by elenfant** [comment]
Náhled a rozumný text - tuším, že FB používá Title tag?

**Comment by SmallhillCZ** [comment]
bohužel používají nějaké meta tagy "og:". problém je, že ty jsou pro celý náš web jednotné a statické (index.html je vždy stejný, obsah se stahuje pomocí javascriptu). takže budu muste udělat nějakou speciální bosan.cz/share/... kde budu separátně generovat stránky obsahující správné og: meta tagy. už se těšim 👎

**Comment by SmallhillCZ** [comment]
Hotovo.
