### ISSUE TITLE
Interní sekce - program - přehled akce - chybí jména vedoucích akce

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#72]
Chybějící jména vedoucích v detailu akce v interní sekci.
https://bosan.cz/interni/akce/5b8d8b0f09a44a1947b9d313/prehled

**Comment by SmallhillCZ** [comment]
Celý přehled jsem prozatím dal pryč a není jasné, jestli se vrátí. Proto prozatím zavírám.
