### ISSUE TITLE
Špatné skloňování

### ISSUE THREAD

**Issue by sosanbosan** [bosancz/bosan.cz#74]
Přijde mi, že je "Kanál v Troje" v programu špatně vyskloňovaný.
Řekl bych spíše "Kanál v Troji"
viz wiki: https://cs.wikipedia.org/wiki/Tr%C3%B3ja

**Comment by elenfant** [comment]
taky jsem si to myslel, ale kdeže: http://prirucka.ujc.cas.cz/?slovo=Troja

**Comment by SmallhillCZ** [comment]
jako nevim.. https://www.supermusic.cz/skupina.php?action=piesen&idpiesne=6556

> Přestal jsem jíst hamburgery, teď jim kila sóji
> Budu největší savec v celý **Praze-Tróji**
> A že tam mám velkou konkurenci....tygry...slony...
> 
> Nejsem, nejsem nejsem nejsem svalnatej
> Ale taky nejsem nejsem vůbec ženatej

**Comment by elenfant** [comment]
jo, mně jde do pusy taky "v Troji" líp než "v Troje", takže jsem pro změnu, akorát ani stávající stav není špatně ;)

**Comment by sosanbosan** [comment]
Hurá, díky. Mně to totiž taky nešlo přes pusu.

**Comment by SmallhillCZ** [comment]
Opraveno podle Leoše.
