### ISSUE TITLE
Galerie - nevracet se na začátek stránky při zavření fotky

### ISSUE THREAD

**Issue by Goliash2** [bosancz/bosan.cz#75]
Při zavření fotky na [https://bosan.cz/fotogalerie](https://bosan.cz/fotogalerie) se mi obrazovka vrátí úplně nahoru stránky na aktuálně nejnovější galerii, i když jsem právě otevřel fotku třeba od dva roky staré akce a já zas musím zpátky scrollovat dolů na pozici, kde jsem v prohlížení skončil.

**Comment by SmallhillCZ** [comment]
Odložim si tu návod: https://next.angular.io/api/router/ExtraOptions

Každopádně funkce řešící tohle přišla do Angularu před dvěma týdny, já jí mám v základu implementovanou, ale trochu čekám, jestli se ještě nějak neusadí, abych nedělal něco zbytečně.
