### ISSUE TITLE
Workflow - akce, galerie, apod.

### ISSUE THREAD

**Issue by SmallhillCZ** [bosancz/bosan.cz#78]
Kdo kdy schvaluje akci k publikaci, kdy mi Tyčka schválí účetnictví atd.

**Comment by jhavelik** [comment]
Akce k publikaci by mělo schvalovat menší množství lidí (tedy vytvořit každý, schválit ty co se starají o program (Leila + ?), vedení, oddíláci?).
Galerie bych nechal vytvářet a publikovat všechny kdo mají účet.
Účetnictví ti schválí Tyčka ve chvíli kdy mu k němu dodáš účtenky + vyplníš správně formulář (aspoň takový je můj dojem),

**Comment by SmallhillCZ** [comment]
Jaký je důvod k tomu, aby mohl akce publikovat jen někdo? Nestačí že si to
treba řekneme? Nejde mi o to to naimplementovat, jen jestli to není
zbytečné omezení, jestli by se opravdu stávalo, že tam někdo bude zakládat
nepovolené akce :-D

**Comment by jhavelik** [comment]
Jde o to že vypsaná akce by měla mít rozumný popisek (podle mě hlavní důvod), tedy pravopisně i obsahově. A to by měl někdo zrevidovat než se to dá veřejně, obodbně jako je tomu v tištěném programu.

**Comment by SmallhillCZ** [comment]
Základ workflow je, zbytek bude v jednotlivých issues.
