### ISSUE TITLE
Vybrat z databáze - špatný default filtr oddílu

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#80]
role i stav nabízí rozumný default, ne tak filtr u oddílu (nejspíš --všechny--)

**Comment by SmallhillCZ** [comment]
co ti to nabízí? mně nic a to je asi správně, ne?

**Comment by elenfant** [comment]
Jojo, nic se nenabízí. Ale čekal bych, že po zadání jména to začne fungovat, teď musím ještě změnit to filtrování.
A ukázalo se, že to je jinak:
- filtr oddíl nemá vliv
- je potřeba změnit __stav__ na __--všichni--__, aby se někdo zobrazil a to bych teda prosil mít tam defaultně..
