### ISSUE TITLE
Interní - galerie - nezobrazují se vůbec alba k editaci

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#81]
V interní sekci se mi po vstupu do části Galerie zobrazuje pouze seznam roků. Po kliknutí na libovolný z nich dostanu HTTP 400 Bad Request (a v tabulce je pořád "Načítám"). Nějaká změna API? 
![image](https://user-images.githubusercontent.com/1541727/45269112-7ec21280-b488-11e8-8118-f2b264473277.png)

**Comment by SmallhillCZ** [comment]
opraveno v bosancz/bosan.cz-server commit 72752fe7a37af5433e2eab59d9ee105013ef98b3
