### ISSUE TITLE
Responzivita webu

### ISSUE THREAD

**Issue by jhavelik** [bosancz/bosan.cz#89]
**O nás**
- [x] buttony v zažij s námi wrapnout - asi nepujde nebo to bootstrap neumim donutit

**Fotogalerie**
- [x] root
- [x] detail alba - dodelat drobeckovou navigaci, at to dava smysl
- [x] detail fotky - dodelat drobeckovou navigaci, at to dava smysl
- [x] hashtagy

**Program**
- [x] mozna nejak poladit mobil
- [x] navigace na pravidelné akce zahezčit, asi nějak takto: https://codepen.io/philcheng/pen/YWyYwG

**Comment by SmallhillCZ** [comment]
- [ ] Interní sekce :)

**Comment by jhavelik** [comment]
@SmallhillCZ vetsina jo, nechavam si jeste otevreny az vyresim galerii a program finalne zavru...

**Comment by SmallhillCZ** [comment]
@jhavelik tak jak to vidíš? :)

**Comment by jhavelik** [comment]
@SmallhillCZ někdy během karantény na to kouknu, nech mi to otevřený
