### ISSUE TITLE
Při pokusu o odeslání invalidního formuláře dát vysvětlující hlášku

### ISSUE THREAD

**Issue by elenfant** [bosancz/bosan.cz#91]
ať změním jakýkoliv field, button "Uložit" je disabled
zjištěno u nově vložených akcí

**Comment by SmallhillCZ** [comment]
Ani když vyplníš typ a charakter akce? Protože to to u mě řeší :)

**Comment by SmallhillCZ** [comment]
každopádně teď nestíhám moc do kdy to potřebuješ?

**Comment by elenfant** [comment]
do besídky :)
a máš pravdu, retard jsem si nevšiml červené linky u těch input boxů... s vyplněním to funguje, takže no stress

**Comment by SmallhillCZ** [comment]
Tenhle formulář bude jen pro správce webu, pro BFU budou "podformuláře" v rámci workflow, které budou návodnější, takže to zavírám.
