### ISSUE TITLE
Nefunguje link v hlavním menu

### ISSUE THREAD

**Issue by sosanbosan** [bosancz/bosan.cz#93]
Nefunguje link v hlavním menu - nezávislé na prohlížeči/rozlišení.
Testováno na desktopu a telefonu.
![image](https://user-images.githubusercontent.com/42980231/46250107-11c0ed80-c434-11e8-8452-edcde59fc3a6.png)

**Comment by SmallhillCZ** [comment]
interesantní, mně funguje :/

**Comment by elenfant** [comment]
mně to taky jede (desktop Chrome Version 69.0.3497.100 (Official Build) (64-bit) a mobil nějaký kdovíjaký Xiaomi Browser V10.0.2)

**Comment by jhavelik** [comment]
@sosanbosan, @elenfant, @SmallhillCZ: jo to bylo nejaky cas na verzi u mě, chtěl jsem aby se při kliknu v mobilním zobrazení zabalilo menu, ale rozbilo to prolinky, někdy proberu s @SmallhillCZ  jestli to půjde nějak vyřešit

**Comment by SmallhillCZ** [comment]
vyřešeno dříve
