### ISSUE TITLE
Návrhy na obsahové změny

### ISSUE THREAD

**Issue by sosanbosan** [bosancz/bosan.cz#94]
**1) http://bosancz-jara.smallhill.cz/o-nas**
`Každý týden se scházíme v naší loděnici Bošán a hrajeme nejrůznější hry`
změnit na ... a přidat proklik na mapu
`Každý týden se scházíme v naší loděnici Bošán v Podolí a hrajeme nejrůznější hry`

**2) http://bosancz-jara.smallhill.cz/program**
`Kam se s námi vypravíš v příštích týdnech.`
doplnit o informaci
`Program je plánován a aktualizován každé 3 měsíce`

**3) http://bosancz-jara.smallhill.cz/aktualne **
`http://bosancz-jara.smallhill.cz/aktualne`
změnil bych na
`Akce na následující měsíc. Celý program zde. /odkaz na program/`

**4) http://bosancz-jara.smallhill.cz/tabor**
`(pro pedanty jako já: nástupiště leží na 804,6 ř.km a převoz na 804,7 ř.km)`
změnit na
`(pro puntíčkáře jako já: nástupiště leží na 804,6 ř.km a převoz na 804,7 ř.km)`
Pedant zní moc přísně podle mě.

**Comment by jhavelik** [comment]
@sosanbosan @elenfant: texty řeší slon, není problém změnit až se dohodneme na finální podobě

**Comment by SmallhillCZ** [comment]
Sry, ale tohle zavírám
