### ISSUE TITLE
Málo hodnocený záznam na google maps

### ISSUE THREAD

**Issue by sosanbosan** [bosancz/bosan.cz#95]
Jen 2x 5 hvězdiček??? Nějaký FB master by měl udělat lepší kampaň ;-)

- [ ] https://www.google.com/maps/place/KONDOR+skupina+%C5%A0%C3%81N/@50.0528014,14.4182772,16.04z/data=!4m5!3m4!1s0x0:0x373f28180deea9b9!8m2!3d50.0506729!4d14.4151475?hl=cs-CZ

- [ ] https://www.firmy.cz/detail/642469-kondor-skupina-san-praha-podoli.html

**Comment by SmallhillCZ** [comment]
netýká se vývoje
