### ISSUE TITLE
Přidání ikony do řádku s menu

### ISSUE THREAD

**Issue by sosanbosan** [bosancz/bosan.cz#96]
Přidání ikony do řádku s menu nalevo od odkazu na web.
Myslím, že by to bylo oživení.
![image](https://user-images.githubusercontent.com/42980231/46250388-58b1e180-c43a-11e8-8474-bc64663db80c.png)

**Comment by jhavelik** [comment]
Přidal jsem do mobilního zobrazení, nějak mě to neuráží, zatím nechám
